config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'

  get '/home',    to: 'static_pages#home'
  get '/about',   to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'

  get '/register', to: 'users#new'

  get    '/login',  to: 'sessions#new'
  post   '/login',  to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  post  'movies/:id/summaries/new' => 'summaries#create'

  # get 'movies' => 'movies#index'
  # get 'movies/:id', to: 'movies#show', as: 'movie'

  resources :users
  resources :summaries
  resources :movies

  resources :movies do
    resources :summaries
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :summaries
  
end

app/models/summary.rb
class Summary < ApplicationRecord
  belongs_to :user

  default_scope -> { order(created_at: :desc) }

  validates :user_id, presence: true
  validates :movie_id, presence: true

  validates :content, presence: true,
            length: { is: 10, tokenizer: -> (str) { str.scan(/\w+/) } }

end

private

def words_in_essay
  essay.scan(/w+/)
end

app/models/user.rb
class User < ApplicationRecord

has_many :summaries, dependent: :destroy

before_save {email.downcase!}

  EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i

  validates :name,
            presence: true,
            length: {maximum: 50}

  validates :email,
            presence: true,
            uniqueness: { case_senstive: false },
            format: { with: EMAIL_REGEX }

  validates :username,
            presence: true,
            uniqueness: { case_senstive: false }

  validates :password,
            presence: true,
            length: {minimum: 8}

  has_secure_password

  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper

  Enceladus.connect("69e30e21886db05709448feb3bf8715b", {
     include_image_language: "pt", language: "en", include_adult: false })

     def logged_in_user
        unless logged_in?
          store_location
          flash[:danger] = "Please log in."
          redirect_to login_url
        end
      end

end

app/controllers/movies_controller.rb
 class MoviesController < ApplicationController

  $popular_movies = Enceladus::Movie.popular

  def index
    @movies = $popular_movies.all
  end

  def show
    @movie = Enceladus::Movie.find(params[:id])
    @summary = current_user.summaries.build if logged_in?
    @sum_list = Summary.find_by(movie_id: @movie.id)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      flash[:success] = 'Login successful'
      log_in(user)
      redirect_to user
    else
      flash.now[:danger] = 'Invalid email/password combination.'
      render 'new'
    end
  end

  def destroy
    log_out if logged_in?
    flash[:info] = 'Logout successful.'
    redirect_to root_url
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end

  def contact
  end

  def movie
  end

end

app/controllers/summaries_controller.rb
class SummariesController < ApplicationController
  before_action :logged_in_user, only: [:create, :destroy]

  def show
    @summary = Summary.find(params[:id])
  end

  def new
    @movie = Enceladus::Movie.find(params[:id])
    @summary = Summary.new(:movie_id => params[:id])
  end

  def create
    @movie = Enceladus::Movie.find(params[:id])
    @summary = current_user.summaries.create(summary_params)

    if @summary.save
      flash[:success] = "Summary created!"
      redirect_to movies_url
    else
      flash[:danger] = "An error has occurred"
      redirect_to movies_url
    end
  end

  def destroy
  end

  private

    def summary_params
      params.require(:summary).permit(:content, :spoiler, :movie_id)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user,        only:   [:show, :edit, :update, :destroy]
  before_action :require_login,   only:   [:edit, :update, :destroy]
  before_action :correct_user,    only:   [:show, :edit, :update, :destroy]
  before_action :require_logout,  only:   [:new]

  # GET /users
  def index
    @users = User.all
  end

  # GET /users/1
  def show
    @user = User.find(params[:id])
    @summaries = @user.summaries.paginate(page: params[:page])
   end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  def create
    @user = User.new(permitted_user_params)
    @user.save

    respond_to do |format|
      if @user.save
        log_in(@user)
        format.html { redirect_to @user, notice: 'User successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def set_user
      @user = User.find(params[:id])
    end

    def permitted_user_params
      params.require(:user).permit(:name, :email, :username, :password, :password_confirmation)
    end

    def require_login
      unless logged_in?
        store_location
        flash[:danger] = "Log in to access this page."
        redirect_to root_url
      end
    end

    def correct_user
      @user = User.find(params[:id])
      unless current_user?(@user)
        flash[:warning] = "No peeking."
        redirect_to root_url
      end
    end

    def require_logout
      if logged_in?
        flash[:warning] = "You're already a registered user."
        redirect_back fallback_location: current_user
    end
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def current_user?(user)
    user == current_user
  end

  def logged_in?
    current_user
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

  # Redirects to stored location (or to the default).
  def redirect_back_or(default)
    redirect_to(session[:forwarding_url] || default)
    session.delete(:forwarding_url)
  end

  # Stores the URL trying to be accessed.
  def store_location
    session[:forwarding_url] = request.original_url if request.get?
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper

  def btn_active(link_path)
   current_page?(link_path) ? "active" : ""
  end

end

app/helpers/users_helper.rb
module UsersHelper

  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>Brevii |
            <%= yield(:title) %></title>
        <%= csrf_meta_tags %>

        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

        <link href="https://fonts.googleapis.com/css?family=Galada" rel="stylesheet">

    </head>

    <body>
        <div class="container">
            <%= render 'partials/header' %>
            <div class="jumbotron">

                <p>
                  <% flash.each do |key, value| %>
                  <div class="alert alert-<%= key %>"><%= value %></div>
                  <% end %>

                    <%= yield %>
                </p>
            </div>

            <%= render 'partials/footer' %>
        </div>
    </div>

</body>
</html>

app/views/movies/index.html.erb
<% provide(:title, "Movies") %>

<body>
    <div class="row">
        <div class="col-lg-12 text-center">

            <div class="input-group search-input col-lg-5 col-md-2 col-md-offset-4">
                <input type="text" class="form-control" ng-model="textFilter" placeholder="Search for a movie!">
                <span class="input-group-btn">
                    <button class="btn btn-info" type="button">Go!</button>
                </span>
            </div>
            <hr>
            <h2 class="page-header">
                Popular Movies</h2>
        </div>
        <% @movies.take(3).each do |movie| %>
        <div class="col-md-4 text-center">
            <div class="thumbnail">
                <%= link_to(image_tag("http://image.tmdb.org/t/p/w300" << movie.poster_path, class: 'img-responsive'), movie_path(movie.id)) %>
                <div class="caption">
                    <h3>
                        <%= movie.title %>
                        <br>
                    </h3>
                    <ul class="list-inline">
                        <li>
                            <!-- #linklinklink -->
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <% end %>
    </div>

</body>

app/views/movies/show.html.erb
<% provide(:title, @movie.title) %>

<% @user = current_user %>

<div class="row">
  <div class="col-sm-4 col-sm-offset-1">
    <%= image_tag("http://image.tmdb.org/t/p/w300" << @movie.poster_path, class: 'img-responsive') %>
  </div>

  <div class="col-sm-6">
      <div class="caption">
          <h3> <%= @movie.title %> </h3>

          <% if @sum_list.present? %>
                  <ol class="reviews">
                      <%= render @sum_list %>
                  </ol>
              <% else %>
                  <p>Movie has no summaries yet.</p>
                  <% end %>

            <div class="row">
                <section class="summary_form">
                  <%= render 'summaries/form' %>
                </section>
            </div>


          <ul class="list-inline">
            <!-- links to deets -->
          </ul>
      </div>
</div>
</div>

app/views/partials/_footer.html.erb
<footer class="footer">
  <div align=right>
    <p>&copy 2016 | <%= link_to "Contact", contact_path %> </p>
  </div>
</footer>

app/views/partials/_header.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">

            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <%= link_to "Brevii", home_path, class:"navbar-brand" %>
        </div>

        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li class="<%= btn_active('/home') %>">
                    <%= link_to "Home", home_path %>
                </li>
                <li>
                <li class="<%= btn_active('/about') %>">
                    <%= link_to "About", about_path %>
                </li>
                <li>
                <li class="<%= btn_active('/movie') %>">
                    <%= link_to "Movies", movies_path %>
                </li>

                <% if logged_in? %>

            <% else %>
                <li class="<%= btn_active('/register') %>">
                    <%= link_to "Register", register_path %>
                </li>
                <% end %>
            </ul>

            <div class="nav navbar-right">
                <ul class="nav navbar-nav">
                    <% if logged_in? %>
                    <div class="btn-group">
                        <button type="button" class="btn btn-sm btn-default">My Account</button>
                        <button type="button" class="btn btn-sm btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <span class="caret"></span>
                            <span class="sr-only">Toggle</span>
                        </button>
                        <ul class="dropdown-menu">
                            <li><%= link_to "View Profile", current_user %></li>
                            <li><%= link_to "Edit Profile", edit_user_path(current_user) %></li>
                            <li class="divider"></li>
                            <li><%= link_to "Log out", logout_path, method: "delete" %></li>
                        </ul>
                    </div>
                </ul>

        <% else %>

            <ul class="nav navbar-nav">
                <%= bootstrap_form_for(:session, url: login_path, layout: :inline) do |f| %>
                <%= f.email_field :email, hide_label: true, placeholder: 'Email' %>
                <%= f.password_field :password, hide_label: true, placeholder: 'Password' %>
                <%= f.submit "Login", class:"btn btn-success"%>
                <% end %>

                <% end %>
            </ul>

          </div>
        </div>
    </nav>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>About</h1>
<p>
  Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>

<h1>Contact</h1>
<p>
Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
</p>

app/views/static_pages/help.html.erb
<h1>Help</h1>
<p>
Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
</p>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>
<h1>Home</h1>
<p>
  This is the home page.
</p>

app/views/static_pages/movie.html.erb
<% provide(:title, "Movies") %>

<h1>Movies</h1>
<p>
Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
</p>

app/views/summaries/_form.html.erb
<%= bootstrap_form_for(@summary, url: new_movie_summary_path(@movie.id), layout: :horizontal) do |f| %>
<%= f.text_field :content, hide_label: true, placeholder: 'Write a summary' %>
<%= f.hidden_field :movie_id, :value => :id %>
<%= f.form_group :spoiler do %>
  <%= f.check_box :spoiler, label: "Spoiler Alert" %>
<% end %>
<%= f.submit "Post", class:"btn btn-info"%>
<% end %>

app/views/summaries/_summary.html.erb
<li id="summary-<%= summary.id %>">
  <%= link_to gravatar_for(summary.user, size: 50), summary.user %>
  <br>
  <span class="user"><%= link_to summary.user.name, summary.user %></span>
  <br>
  <span class="content"><%= summary.content %></span>
  <br>
  <span class="timestamp">
    Posted on <%=summary.created_at%>
  </span>
</li>

app/views/summaries/index.html.erb
<li id="summary-<%= summary.id %>">
  <span class="user"><%= link_to summary.user.name, summary.user %> wrote:</span>
  <span class="summary"><%= summary.movie %></span>
  <span class="content"><%= summary.content %></span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(summary.created_at) %> ago.
  </span>
</li>

app/views/users/edit.html.erb
<% provide(:title, "Edit Profile") %>
<h1>Update your profile</h1>

<div class="gravatar_edit">
 <%= gravatar_for @user %>
 <a href="http://gravatar.com/emails" target="_blank">change</a>
</div>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Save changes", class: "btn btn-primary" %>
    <% end %>

  </div>
</div>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Username</th>
      <th>Action</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.username %></td>
        <td><%= link_to 'Show', user %> |
            <%= link_to 'Edit', edit_user_path(user) %> |
            <%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Add New User', new_user_path %>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<div class="container">

    <%= bootstrap_form_for(@user, layout: :horizontal, label_col: "col-sm-3", control_col: "col-sm-6") do |f| %>

        <%= f.text_field :name %>
        <%= f.email_field :email  %>
        <%= f.text_field :username %>
        <%= f.password_field :password, help: "Must be at least 8 characters long" %>
        <%= f.password_field :password_confirmation, label: "Confirm Password"%>

        <%= f.submit "Register", class: "btn btn-large btn-primary" %>

        <% end %>

</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>

<div class="row">
  <aside class="col-md-6">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>

<br>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>

<p>
  <strong>Password:</strong>
  <%= link_to 'Click to change', edit_user_path(@user) %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

</aside>

<div class="col-md-6">
  <% if @user.summaries.any? %>
    <h3>Summaries (<%= @user.summaries.count %>)</h3>
    <ol class="reviews">
      <%= render current_user.summaries %>
    </ol>
  <% else %>
    <p>User has not posted any summaries.</p>
  <% end %>
</div>
</div>